name: 'Run autobump'
inputs:

  glob:
    type: string
    required: true

  labels:
    type: string
    required: false
    default: autobump
    description: A comma or newline-separated list of labels.

runs:

  using: "composite"
  steps:

    - name: Set GitHub Path
      run: echo "$GITHUB_ACTION_PATH" >> $GITHUB_PATH
      shell: bash
      env:
        GITHUB_ACTION_PATH: ${{ github.action_path }}

    - run: python autobump.py --glob ${{ fromJSON(inputs.glob) }}
      shell: bash

    - name: Create pull request
      uses: peter-evans/create-pull-request@v7
      with:
        title: Autobump ${{ github.event.repository.updated_at}}
        labels: ${{ inputs.labels }}
