name: 'Run autobump'
inputs:

  branch:
    type: string
    required: false
    default: ''
    description: The name of the branch where the changes should be pushed. Defaults to `autobump/uuid` where the `uuid` is randomly generated.

  glob:
    type: string
    required: true
    default: '*'

  labels:
    type: string
    required: false
    default: autobump
    description: A comma or newline-separated list of labels.

  base:
    type: string
    required: false
    default: ''
    description: The name of the base branch of the pull request.

outputs:

  branch:
    description: The branch name where the changes were pushed.
    value: ${{ steps.pr_meta.outputs.branch }}

  pull-request-number:
    description: The pull request number.
    value: ${{ steps.create-pull-request.outputs.pull-request-number }}

  pull-request-url:
    description: The URL of the pull request.
    value: ${{ steps.create-pull-request.outputs.pull-request-url }}

runs:

  using: "composite"
  steps:

    - name: Set GitHub Path
      run: echo "$GITHUB_ACTION_PATH" >> $GITHUB_PATH
      shell: bash
      env:
        GITHUB_ACTION_PATH: ${{ github.action_path }}

    - run: autobump.py --glob "${{ inputs.glob }}" --verbose --summary "$GITHUB_OUTPUT"
      shell: bash
      id: autobump

    - run: |
        if [ "${{ inputs.branch == '' }}" = "" ]; then
          echo "branch=autobump/$(uuidgen)" >> "$GITHUB_OUTPUT"
        else
          echo "branch=${{ inputs.branch }}" >> "$GITHUB_OUTPUT"
        fi
      shell: bash
      id: pr_meta

    - name: Create pull request
      uses: peter-evans/create-pull-request@v7
      id: create-pull-request
      with:
        title: Autobump ${{ github.event.repository.updated_at }}
        labels: ${{ inputs.labels }}
        body: Autobump by [kostrykin/autobump-action](https://github.com/kostrykin/autobump-action)
        branch: ${{ steps.pr_meta.outputs.branch }}
        commit-message: Autobump ${{ steps.autobump.outputs.changed-files-count }} file(s)
        base: ${{ inputs.base }}