name: 'Run auto-bump'
inputs:

  glob:
    type: string
    required: true

runs:

  using: "composite"
  steps:

    - name: Set GitHub Path
      run: echo "$GITHUB_ACTION_PATH" >> $GITHUB_PATH
      shell: bash
      env:
        GITHUB_ACTION_PATH: ${{ github.action_path }}

    - run: python autobump.py --glob ${{ fromJSON(inputs.glob) }}
      shell: bash

    - name: Create pull request
      uses: peter-evans/create-pull-request@v7
