name: 'Run autobump'
inputs:

  glob:
    type: string
    required: true
    default: '*'

  labels:
    type: string
    required: false
    default: autobump
    description: A comma or newline-separated list of labels.

outputs:

  branch:
    description: The branch name where the changes were pushed.
    value: ${{ steps.branch.outputs.branch }}

  pull-request-number:
    description: The pull request number.
    value: ${{ steps.create-pull-request.outputs.pull-request-number }}

  pull-request-url:
    description: The URL of the pull request.
    value: ${{ steps.create-pull-request.outputs.pull-request-url }}

runs:

  using: "composite"
  steps:

    - name: Set GitHub Path
      run: echo "$GITHUB_ACTION_PATH" >> $GITHUB_PATH
      shell: bash
      env:
        GITHUB_ACTION_PATH: ${{ github.action_path }}

    - run: python autobump.py --glob "${{ inputs.glob }}" --verbose --summary "$GITHUB_OUTPUT"
      shell: bash
      id: autobump

    - run: echo "branch=autobump/$(uuidgen)" >> "$GITHUB_OUTPUT"
      shell: bash
      id: branch

    - name: Create pull request
      uses: peter-evans/create-pull-request@v7
      id: create-pull-request
      with:
        title: Autobump ${{ github.event.repository.updated_at}}
        labels: ${{ inputs.labels }}
        body: Autobump by [kostrykin/autobump-action](https://github.com/kostrykin/autobump-action)
        branch: ${{ steps.branch.outputs.branch }}
        commit-message: Autobump ${{ steps.autobump.outputs.changed-files-count }} file(s)
