name: Update tags

on:
  push:
    tags: 'v*'

jobs:
  release:
    name: 'Release'
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: write

    steps:
      - name: Update Tags
        uses: cssnr/update-version-tags-action@v1.2