name: Test

on:
  workflow_dispatch:
  push:
    branches: ['master']

permissions:
  contents: write
  pull-requests: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4

      - run: python .github/setup-test.py
        shell: bash

      - uses: ./
        id: autobump
        with:
          labels: autobump-test

      - run: git checkout "${{ steps.autobump.outputs.pull-request-branch }}"
        shell: bash

      - uses: peter-evans/close-pull@v3
        with:
          pull-request-number: ${{ steps.autobump.outputs.pull-request-number }}
          comment: Auto-closing pull request
          delete-branch: true