name: Test

on:
  workflow_dispatch:
  pull_request:
    branches: ['master']
    paths:
      - '.github/workflows/test.yml'
      - 'action.yml'
      - '**/*.py'
  push:
    branches: ['master']
    paths:
      - '.github/workflows/test.yml'
      - 'action.yml'
      - '**/*.py'

permissions:
  contents: write
  pull-requests: write

jobs:
  test-glob:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4

      - run: python .github/setup-test.py
        shell: bash

      - uses: ./
        id: autobump
        with:
          base: ${{ github.event.repository.default_branch }}
          glob: |
            .github/*.txt
            .github/*.md
          labels: autobump-test

      - uses: peter-evans/close-pull@v3
        with:
          pull-request-number: ${{ steps.autobump.outputs.pull-request-number }}
          comment: Closing autobump-test pull request
          delete-branch: true

      - run: echo "<${{ steps.autobump.outputs.pull-request-url }}>" >> $GITHUB_STEP_SUMMARY

  test-no-changes:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4

      - uses: ./
        id: autobump
        with:
          base: ${{ github.event.repository.default_branch }}
          glob: LICENSE
      
      - run: exit 1
        if: ${{ steps.autobump.outputs.pull-request-number != '' }}
  
  test-input-branch:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4

      - run: python .github/setup-test.py
        shell: bash

      - uses: ./
        id: autobump
        with:
          base: ${{ github.event.repository.default_branch }}
          glob: |
            .github/*.txt
            .github/*.md
          branch: autobump/input-branch

      - uses: peter-evans/close-pull@v3
        with:
          pull-request-number: ${{ steps.autobump.outputs.pull-request-number }}
          comment: Closing autobump-test pull request
          delete-branch: true

      - run: exit 1
        shell: bash
        if: ${{ steps.autobump.outputs.branch != 'autobump/input-branch' }}

      - run: echo "<${{ steps.autobump.outputs.pull-request-url }}>" >> $GITHUB_STEP_SUMMARY