name: Test

on:
  workflow_dispatch:
  push:
    branches: ['master']

jobs:
  test:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4

      - uses: ./
        id: autobump

      - uses: peter-evans/close-pull@v3
        with:
          pull-request-number: ${{ steps.autobump.outputs.pull-request-number }}
          comment: Auto-closing pull request
          delete-branch: true