name: Test

on:
  workflow_dispatch:
  push:
    branches: ['master']
    paths:
      - '.github/workflows/test.yml'
      - 'action.yml'
      - '**/*.py'

permissions:
  contents: write
  pull-requests: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4

      - run: python .github/setup-test.py
        shell: bash

      - uses: ./
        id: autobump
        with:
          glob: .github/*
          labels: autobump-test

      - uses: peter-evans/close-pull@v3
        with:
          pull-request-number: ${{ steps.autobump.outputs.pull-request-number }}
          comment: Closing autobump-test pull request
          delete-branch: true

      - run: echo "<${{ steps.autobump.outputs.pull-request-url }}>" >> $GITHUB_STEP_SUMMARY
